"""Added tables for storing information about GenomicsDS instances and partitions

Revision ID: 5a0f5bac9ebd
Revises: 4631177f4ecc
Create Date: 2017-05-12 19:00:18.091025

"""

# revision identifiers, used by Alembic.
revision = '5a0f5bac9ebd'
down_revision = '4631177f4ecc'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genomicsds_instance',
    sa.Column('id', sa.BigInteger, nullable=False),
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('reference_set_id', sa.BigInteger, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['reference_set_id'], ['reference_set.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guid')
    )
    op.create_table('genomicsds_partition',
    sa.Column('id', sa.BigInteger, nullable=False),
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('genomicsds_instance_id', sa.BigInteger, nullable=False),
    sa.Column('data_store_type', sa.Enum('tiledb_on_disk_array', name='genomicsds_partition_data_store_types_enum'), server_default='tiledb_on_disk_array', nullable=False),
    sa.Column('workspace_id', sa.BigInteger, nullable=True),
    sa.Column('db_array_id', sa.BigInteger, nullable=True),
    sa.CheckConstraint(u"data_store_type = 'tiledb_on_disk_array' AND workspace_id IS NOT NULL AND db_array_id IS NOT NULL", name='type_to_null_constraint'),
    sa.ForeignKeyConstraint(['db_array_id'], ['db_array.id'], ),
    sa.ForeignKeyConstraint(['genomicsds_instance_id'], ['genomicsds_instance.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guid')
    )
    op.add_column(u'workspace', sa.Column('machines', sa.Text(), server_default='*', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'workspace', 'machines')
    op.drop_table('genomicsds_partition')
    op.drop_table('genomicsds_instance')
    op.execute('DROP TYPE IF EXISTS genomicsds_partition_data_store_types_enum')
    ### end Alembic commands ###
