"""Set num_rows,tiledb_column server side defaults

Revision ID: 389236a48cd4
Revises: efa5e584648
Create Date: 2015-12-16 14:04:59.172563

"""

# revision identifiers, used by Alembic.
revision = '389236a48cd4'
down_revision = 'efa5e584648'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reference_set', 'next_tiledb_column_offset',
                    server_default=sa.text('0'))
    op.alter_column('db_array', 'num_rows', server_default=sa.text('0'))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
